module.exports = {
    videodata: [{
            id: 101,
            name: "iPhone 11 Unboxing & First Look - A Solid Champ?",
            duration: { m: 08, s: 27 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwngAg8C9ez6SdBMdgEA-Aud61obXOuY1zsUPkL8Z0w=s68-c-k-c0x00ffffff-no-rj",
                name: "Technical Guruji",
            },
            description: "Namaskaar Dosto, is video mein maine aapse baat ki hai Apple ke latest iPhone 11 family ke baare mein jaha pe hai latest iPhone 11, iPhone 11 Pro aur iPhone 11 Pro Max. Yaha maine share ki hai Unboxing video Apple iPhone 11 ki jo ek update hai iPhone Xr ke baad mein, yaha pe kaafi ",
            views: "4,869,505 views",
            date: "19 Sept 2019",
            videourl: "https://youtube.com/embed/hXeI5zVN_gM",
            brand: "Apple",
            type: "Unboxing",
        },
        {
            id: 102,
            name: "iPhone 12 Review: Just Got Real!",
            duration: { m: 18, s: 17 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwngW9TQgw7E7NqS3Qzd3Up3tjUzkpvMXPWAhYf3LaQ=s88-c-k-c0x00ffffff-no-rj",
                name: "Marques Brownlee",
            },
            description: "iPhone 12 is the first of a lot of things for the iPhone. It's pretty damn good.",
            views: "9,719,916 views",
            date: "26 Oct 2020",
            videourl: "https://youtube.com/embed/X1b3C2081-Q",
            brand: "Apple",
            type: "Review",
        },
        {
            id: 103,
            name: "iPhone 12 Vs iPhone 11 pro",
            duration: { m: 13, s: 55 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwnhj1JGcrMgWlOOAjkNpFPwbfIFJdE1ueprrlRDjJA=s88-c-k-c0x00ffffff-no-rj",
                name: "HFV Unbox",
            },
            description: "Hello !! Today in this video I am sharing my opinion about iPhone 12 and iPhone 11 pro.",
            views: "240,340 views",
            date: "1 Nov 2020",
            videourl: "https://youtube.com/embed/rd2CwtPDq6Y",
            brand: "Apple",
            type: "Comparison",
        },
        {
            id: 104,
            name: "iPhone 12 Hidden Features - Top 12 List",
            duration: { m: 35, s: 47 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwng62LxnJpF3UFzsGvnn9XwzrW_Se2P8QdLfzEhd=s88-c-k-c0x00ffffff-no-rj",
                name: "AppFind",
            },
            description: "Watch this video to see the best Hidden iPhone 12 Features. Including over 12 Hidden Features, Tips, and Tricks for your iPhone 12, iPhone 12 Pro, iPhone 12 Mini & iPhone 12 Pro Max! This video includes the Best Hidden Features for the iPhone 12.",
            views: "273,981 views",
            date: "25 Oct 2020",
            videourl: "https://youtube.com/embed/6nUzbfOGC9Q",
            brand: "Apple",
            type: "Review",
        },
        {
            id: 105,
            name: "REDMI NOTE 8 PRO FULL REVIEW",
            duration: { m: 10, s: 00 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwnjPf0emeS2V-RvpO8Q_iFn-qI3WDEy_JnKPU9LmUg=s88-c-k-c0x00ffffff-no-rj",
                name: "Trakin Tech",
            },
            description: "Hello Friends, Aaj Ke Video Mein Humne Kiya Hain Redmi Note 8 Pro ka Full Details Reviews 15 Dino Tak Use Karne Ke Baad. Redmi Note 8 Pro Definately Ek Performance Powerhouse Hain Kya Likin Kya Ye Overall Ek Accha Smartphone Hain? Ye Video Ant Tak Dekhiye Aur Video Ko Like Aur Share Karna na Bhoole.",
            views: "1,888,850 views",
            date: "25 Oct 2019",
            videourl: "https://youtube.com/embed/okdbsJ1IkKw",
            brand: "Redmi",
            type: "Review",
        },
        {
            id: 106,
            name: "Redmi Note 9 Pro Max Unboxing And First Impressions",
            duration: { m: 09, s: 20 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwnjPf0emeS2V-RvpO8Q_iFn-qI3WDEy_JnKPU9LmUg=s88-c-k-c0x00ffffff-no-rj",
                name: "Trakin Tech",
            },
            description: "Hello Friends, Aaj Ke Video Me We Are Doing The Unboxing Of Redmi Note 9 Pro Max. Akhir Kya Hain Iss Phone Me? Ye Video Ant Tak Dekhiye Aur Janiye Redmi Note 9 Pro Max Ke Baare Me Sabkuch. Agar Aapko Ye Video Accha Laga To Video Ko Like Aur Share Karna Na Bhoole.",
            views: "3,609,719 views",
            date: "14 May 2020",
            videourl: "https://youtube.com/embed/gjpytFNGbIU",
            brand: "Redmi",
            type: "Unboxing",
        },
        {
            id: 107,
            name: "Redmi 9 Power Indian Unit Unboxing & First Impressions",
            duration: { m: 07, s: 32 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwnjPf0emeS2V-RvpO8Q_iFn-qI3WDEy_JnKPU9LmUg=s88-c-k-c0x00ffffff-no-rj",
                name: "Trakin Tech",
            },
            description: "Doston Redmi 9 Power Is Finally Launched In India, It packs some good specs for the price. SD 662, 6000mAh Battery, FHD+ Screen And More. To Ye Video Aap Ant Tak Dekhiye Aur Video Ko Like Aur Share karna na bhoole. ",
            views: "858,931 views",
            date: "21 Dec 2020",
            videourl: "https://youtube.com/embed/hoPC8V4X0do",
            brand: "Redmi",
            type: "Unboxing",
        },

        {
            id: 108,
            name: "Redmi Note 10 Pro Max Detailed FAQ",
            duration: { m: 10, s: 34 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwnjPf0emeS2V-RvpO8Q_iFn-qI3WDEy_JnKPU9LmUg=s88-c-k-c0x00ffffff-no-rj",
                name: "Trakin Tech",
            },
            description: "Redmi Note 10 Pro Max ke Unboxing video par humein Kai sawaal aaye, aur isliye is video mein hum de rahe hai aapko un sabhi sawalon ke seedhe jawab. Ye video dekhne ke baad apko sabkuch pataa chal jaayega Redmi Note 10 Pro Max is phone ke bare mein. Agar Aap Future Me Aise He FAQ Videos Dekhana Chahte Hain To Comments Me Jaroor Bataye.",
            views: "394,332 views",
            date: "13 Mar 2021",
            videourl: "https://youtube.com/embed/RbbGagvnZ1I",
            brand: "Redmi",
            type: "Review",
        },
        {
            id: 109,
            name: "Samsung Galaxy F41 Unboxing And First Impressions",
            duration: { m: 08, s: 13 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwnjPf0emeS2V-RvpO8Q_iFn-qI3WDEy_JnKPU9LmUg=s88-c-k-c0x00ffffff-no-rj",
                name: "Trakin Tech",
            },
            description: "Hello Doston Aaj Ke Video Me Hum Aapko Kar Rahe Hain All New Samsung Galaxy F41 Ko Unbox. Do Watch This Video Till The End. Video Ko Like Aur Share Karna Na Bhoole.",
            views: "1,558,993 views",
            date: "8 Oct 2020",
            videourl: "https://youtube.com/embed/_qL2mTVkg8c",
            brand: "Samsung",
            type: "Unboxing",
        },
        {
            id: 110,
            name: "Samsung Galaxy M51 Unboxing & First Look",
            duration: { m: 07, s: 31 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwngAg8C9ez6SdBMdgEA-Aud61obXOuY1zsUPkL8Z0w=s88-c-k-c0x00ffffff-no-rj",
                name: "Technical Guruji",
            },
            description: "Namaskaar Dosto, is video mein maine aapse baat ki hai Samsung ke brand new Galaxy M Series ke latest phone #GalaxyM51​ ke baare mein, aur share ki hai isi Galaxy M51 smartphone ki ek unboxing aur ek first look, baat kare kuch details isi Galaxy M51 ke baare mein yaha hume ek 6.7 ka ek FHD+ Super AMOLED Plus Display milta hai Infinity-O cut ke saath, iske alawa is mein hai Qualcomm Snapdragon 730G Octacore Processor aur option hai 6GB/8GB RAM ka 128GB storage ke saath mein. Isme aapko ek improved 64MP Quad Rear Camera setup milta hai 64MP Primary, 12MP Ultrawide aur 5MP Depth Camera + 5MP Macro Camera ke saath, aur ek 32MP ka selfie camera hai, aur finally 7000mAh ki badi battery USB-C Port aur Samsung ki 25Watt Super Fast charging ke saath. Samsung is Galaxy M51 ko kehta hai #MeanestMonsterEver​. Mujhe umeed hai ki aapko Samsung Galaxy M51 ki yeh unboxing aur ek first look video video pasand aayegi.",
            views: "3,095,561 views",
            date: "10 Sept 2020",
            videourl: "https://youtube.com/embed/UGjOzK9TdHA",
            brand: "Samsung",
            type: "Unboxing",
        },
        {
            id: 111,
            name: "Samsung GALAXY M31 - Camera Review",
            duration: { m: 13, s: 25 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwnh8lps2C9kLao5eSYJkgsAPWY_qyfi17uBkrRm63w=s88-c-k-c0x00ffffff-no-rj",
                name: "Technical Sky",
            },
            description: "#Samsung #GALAXY #M31 - Camera Review",
            views: "298,624 views",
            date: "23 Mar 2020",
            videourl: "https://youtube.com/embed/F-L1HsNIV5w",
            brand: "Samsung",
            type: "Review",
        },
        {
            id: 112,
            name: "Samsung Galaxy S10 First Look & Feature Overview",
            duration: { m: 04, s: 45 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwngAg8C9ez6SdBMdgEA-Aud61obXOuY1zsUPkL8Z0w=s88-c-k-c0x00ffffff-no-rj",
                name: "Technical Guruji",
            },
            description: "Namaskaar Dosto, is video mein maine aapse Samsung Galaxy S10 ke baare mein baat ki hai, humne first look dekha hai Galaxy S10 ka aur dekha hai isi phone aur detail mein jaha aapko milta hai 6.1 ka QHD+ Infinity O Dynamic AMOLED Display HDR10+ ke saath mein, Triple Rear Camera Setup 12MP+12MP+16MP, jaha 12MP Main Camera variable aperture ke saath, 12MP Telephoto Camera, aur ek 16MP Ultra Wide Camera, isme Front Facing Camera hai 10MP ka. Samsung ne S10 ki price rakhi hai 66,900Rs se shuru India mein. S10 mein 8GB aur 128GB/512GB Storage options available hai. S10 mein 3400mAh ki battery hai jaha Fast Charging, Fast Wireless Charging aur Reverse wireless charging options available hai. Mujhe umeed hai ki aapko Galaxy S10 ke yeh first look ki yeh video pasand aayegi.",
            views: "916,686 views",
            date: "23 Feb 2019",
            videourl: "https://youtube.com/embed/aHOyzJ_g-Fw",
            brand: "Samsung",
            type: "Unboxing",
        },
        {
            id: 113,
            name: "OnePlus Nord vs OnePlus 7T vs OnePlus 8: Comparison overview",
            duration: { m: 07, s: 30 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwniBKyCFx0OHnq6wxb6KmNNWHFXMgacvmiwKC-tB=s88-c-k-c0x00ffffff-no-rj",
                name: "91mobiles",
            },
            description: "Hello everyone, this is Keshav Khera and in this video, I will tell you about Oneplus Nord vs Oneplus 7T vs Oneplus 8. Oneplus Nord is available in India now. In this comparison, I will talk about Oneplus Nord specifications compared with Oneplus 7T specifications and Oneplus 8 specification.",
            views: "214,632 views",
            date: "27 Jul 2020",
            videourl: "https://youtube.com/embed/xPO3bHTPo3I",
            brand: "Oneplus",
            type: "Comparison",
        },
        {
            id: 114,
            name: "The TRUTH About OnePlus Nord!",
            duration: { m: 10, s: 19 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwngW9TQgw7E7NqS3Qzd3Up3tjUzkpvMXPWAhYf3LaQ=s88-c-k-c0x00ffffff-no-rj",
                name: "Marques Brownlee",
            },
            description: "OnePlus Nord was inevitable. Here's why",
            views: "3,895,294 views",
            date: "28 Jul 2020",
            videourl: "https://youtube.com/embed/Xzh8BdaaAvs",
            brand: "Oneplus",
            type: "Review",
        },
        {
            id: 115,
            name: "OnePlus 9 Series - Everything You Need To Know",
            duration: { m: 09, s: 52 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwngimkR1F2K9aDtndM7g610c1AeeYaOJlxRrikJ2Aw=s88-c-k-c0x00ffffff-no-rj",
                name: "TipTop Tech",
            },
            description: "Oneplus 9 Series is down the line to it's launch and this time the name of the game is superior camera system. The Oneplus 9 series will have Three Devices named as Oneplus 9 Pro , Oneplus 9 and the Oneplus 9R.",
            views: "192,849 views",
            date: "15 Mar 2021",
            videourl: "https://youtube.com/embed/bByr38I71H8",
            brand: "Oneplus",
            type: "Review",
        },
        {
            id: 116,
            name: "Oneplus 8T vs Oneplus 8, 8 Pro FULL Comparison",
            duration: { m: 22, s: 42 },
            postedby: {
                icon: "https://yt3.ggpht.com/ytc/AAUvwnjLrXgue6Lz1K7pkqotAwys261xk1lH7FtiyHG4=s88-c-k-c0x00ffffff-no-rj",
                name: "MySmartPrice",
            },
            description: "Oneplus 8 T Price in India Starts at Rs 42,999. In this video we do a three way comparison between Oneplus 8T vs Oneplus 8 vs Oneplus 8 Pro. We do a Oneplus 8T vs 8 Pro Camera Comparison, Oneplus 8T vs 8 Pro speed test, Oneplus 8 Pro vs Oneplus 8T camera comparison and Oneplus 8 vs Oneplus 8T which phone to buy. Overall this video will solve all your queries about Oneplus 8T vs 8, Oneplus 8T vs Oneplus 8 Pro, Oneplus 8 vs 8T and Oneplus 8T vs Oneplus8.",
            views: "924,854 views",
            date: "16 Oct 2020",
            videourl: "https://youtube.com/embed/ia2ozfsn708",
            brand: "Oneplus",
            type: "Comparison",
        },
    ],
    filters: [{
            type: "brand",
            value: "Apple",
        },
        {
            type: "brand",
            value: "Redmi",
        },
        {
            type: "brand",
            value: "Samsung",
        },
        {
            type: "brand",
            value: "Oneplus",
        },
        {
            type: "type",
            value: "Unboxing",
        },
        {
            type: "type",
            value: "Review",
        },
        {
            type: "type",
            value: "Comparison",
        },

    ],
    brands: ["Apple", "Redmi", "Samsung", "Oneplus"],
    type: ["Unboxing", "Review", "Comparison"],
};